In [83]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
import os
from termcolor import colored
from scipy import stats
import plotly.express as px
from plotly.figure_factory import create_scatterplotmatrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [116]:
data = pd.read_csv("/content/diabetes_data.csv")

X = data.drop('Diabetes', axis=1)
y = data['Diabetes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

data_train = pd.concat([X_train, y_train], axis=1)
data_test = pd.concat([X_test, y_test], axis=1)

In [117]:
model1 = LogisticRegression()

model1.fit(X_train, y_train)

y_pred = model1.predict(X_test)

print('Recall: ', recall_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred))
print('Accuracy: ', accuracy_score(y_test, y_pred))

confusion_matrix(y_test, y_pred)

Recall:  0.7753155680224404
Precision:  0.7410187667560322
Accuracy:  0.7500471520181063


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[7615, 2898],
       [2403, 8292]])

In [118]:
model2 = smf.glm(formula = 'Diabetes ~ Age + Sex + HighChol + CholCheck + BMI + Smoker + HeartDiseaseorAttack + PhysActivity + Fruits + Veggies + HvyAlcoholConsump + GenHlth + MentHlth + PhysHlth + DiffWalk + Stroke + HighBP', data = data_train, family=sm.families.Binomial()).fit()

y_proba = model2.predict(data_test)
y_pred = y_proba.apply(lambda x: 1 if x > 0.5 else 0)

print('Recall: ', recall_score(data_test['Diabetes'], y_pred))
print('Precision: ', precision_score(data_test['Diabetes'], y_pred))
print('Accuracy: ', accuracy_score(data_test['Diabetes'], y_pred))

confusion_matrix(y_test, y_pred)

Recall:  0.7785881252921926
Precision:  0.7455457068672218
Accuracy:  0.7543379856657865


array([[7671, 2842],
       [2368, 8327]])

In [119]:
model3 = smf.glm(formula = 'Diabetes ~ Age + HighChol + BMI + HeartDiseaseorAttack + PhysActivity + GenHlth + PhysHlth + DiffWalk + HighBP', data = data_train, family=sm.families.Binomial()).fit()

y_proba = model3.predict(data_test)
y_pred = y_proba.apply(lambda x: 1 if x > 0.5 else 0)

print('Recall: ', recall_score(data_test['Diabetes'], y_pred))
print('Precision: ', precision_score(data_test['Diabetes'], y_pred))
print('Accuracy: ', accuracy_score(data_test['Diabetes'], y_pred))

confusion_matrix(y_test, y_pred)

Recall:  0.7752220663861618
Precision:  0.7409294012511171
Accuracy:  0.7499528479818937


array([[7614, 2899],
       [2404, 8291]])

In [96]:
model4 = smf.glm(formula = 'Diabetes ~ Age + HighChol + CholCheck + BMI + HeartDiseaseorAttack + PhysActivity + GenHlth + PhysHlth + DiffWalk + Stroke + HighBP', data = data_train, family=sm.families.Binomial()).fit()

y_proba = model4.predict(data_test)
y_pred = y_proba.apply(lambda x: 1 if x > 0.5 else 0)

print('Recall: ', recall_score(data_test['Diabetes'], y_pred))
print('Precision: ', precision_score(data_test['Diabetes'], y_pred))
print('Accuracy: ', accuracy_score(data_test['Diabetes'], y_pred))

confusion_matrix(y_test, y_pred)

Recall:  0.766195856873823
Precision:  0.7389882844428299
Accuracy:  0.7474066390041494


array([[7714, 2874],
       [2483, 8137]])

In [95]:
model5 = smf.glm(formula = 'Diabetes ~ Age + HighChol + BMI + HeartDiseaseorAttack + PhysActivity + GenHlth*PhysHlth + DiffWalk + HighBP', data = data_train, family=sm.families.Binomial()).fit()

y_proba = model5.predict(data_test)
y_pred = y_proba.apply(lambda x: 1 if x > 0.5 else 0)

print('Recall: ', recall_score(data_test['Diabetes'], y_pred))
print('Precision: ', precision_score(data_test['Diabetes'], y_pred))
print('Accuracy: ', accuracy_score(data_test['Diabetes'], y_pred))

confusion_matrix(y_test, y_pred)

Recall:  0.7657250470809793
Precision:  0.7362607514712539
Accuracy:  0.7453319502074689


array([[7675, 2913],
       [2488, 8132]])

In [94]:
model6 = smf.glm(formula = 'Diabetes ~ Age + HighChol + CholCheck + BMI + Smoker + HeartDiseaseorAttack + PhysActivity + Veggies + HvyAlcoholConsump + GenHlth + MentHlth + PhysHlth + DiffWalk + Stroke + HighBP', data = data_train, family=sm.families.Binomial()).fit()

y_proba = model6.predict(data_test)
y_pred = y_proba.apply(lambda x: 1 if x > 0.5 else 0)

print('Recall: ', recall_score(data_test['Diabetes'], y_pred))
print('Precision: ', precision_score(data_test['Diabetes'], y_pred))
print('Accuracy: ', accuracy_score(data_test['Diabetes'], y_pred))

confusion_matrix(y_test, y_pred)

Recall:  0.7670433145009417
Precision:  0.7400072674418605
Accuracy:  0.7483968313843833


array([[7726, 2862],
       [2474, 8146]])

In [122]:
model7 = smf.glm(formula = 'Diabetes ~ Age + HighChol + BMI + HeartDiseaseorAttack + PhysActivity + GenHlth + PhysHlth + DiffWalk + HighBP', data = data_train, family=sm.families.Binomial()).fit()

y_proba = model7.predict(data_test)
y_pred = y_proba.apply(lambda x: 1 if x > 0.5 else 0)

print('Recall: ', recall_score(data_test['Diabetes'], y_pred))
print('Precision: ', precision_score(data_test['Diabetes'], y_pred))
print('Accuracy: ', accuracy_score(data_test['Diabetes'], y_pred))

confusion_matrix(y_test, y_pred)

Recall:  0.7752220663861618
Precision:  0.7409294012511171
Accuracy:  0.7499528479818937


array([[7614, 2899],
       [2404, 8291]])